apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: artifactory
spec:
  interval: 5m
  url: https://sky.jfrog.io/sky/helm/
  secretRef:
    name: jfrog
---
apiVersion: v1
kind: Secret
metadata:
  name: jfrog
  namespace: flux-system
data:
  username: Y29vcGVybWlj
  password: QUtDcDVkS3NlR0VMREZGYnMzSlVReFpKTURMN2NwMWNpWnNIanZtZE1WalBVQ3FQaldzWDlrMjlIZ2g1WDluQnJFYkUyVm5BTg==